name: business_card_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  sms_otp_auto_verify: ^2.1.0
  flutter_screenutil: ^5.9.0
  cupertino_onboarding: ^1.2.0
  bottom_sheet: ^4.0.0
  flutter_onboarding_slider: ^1.0.11
  flutter_pin_code_fields: ^2.2.0
  qr_scanner_with_effect: ^1.0.5
  flutter_barcode_scanner: ^2.0.0
  buttons_tabbar: ^1.3.8
  scan: ^1.6.0
  http: ^1.1.0
  rflutter_alert: ^2.0.7
  shimmer: ^3.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  shared_value: ^3.0.0
  molten_navigationbar_flutter: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  alphabet_list_scroll_view_fix: ^2.0.2
  get: 4.6.6
  share_plus: ^7.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/q.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bottom_sheet/
    - assets/images/on_board/
    - assets/images/bottom_nav_bar/
    - assets/images/login_page/
    - assets/images/settings/
    - assets/images/screen_top/
    - assets/images/act_details/
    - assets/images/contact/
    - assets/images/card_model/

  fonts:
    - family: SfBold
      fonts:
        - asset: assets/fonts/sf-pro-text-bold.ttf
    - family: SfHeavy
      fonts:
        - asset: assets/fonts/sf-pro-text-heavy.ttf
    - family: SfLight
      fonts:
        - asset: assets/fonts/sf-pro-text-light.ttf
    - family: SfMedium
      fonts:
        - asset: assets/fonts/sf-pro-text-medium.ttf
    - family: SfRegular
      fonts:
        - asset: assets/fonts/sf-pro-text-regular.ttf
    - family: SfSemiBold
      fonts:
        - asset: assets/fonts/sf-pro-text-semibold.ttf
